import Testing
import Foundation
@testable import PLzmaSDK

// xzip additions: the BZip2 / Deflate / Deflate64 decoders and the operation result carried in an
// item failure's reason. Fixtures are in Fixtures/xzip, regenerated by make7z.py there; every
// archive that decodes is compared byte for byte with the payload it was made from.

private let fixtures = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
    .appendingPathComponent("Fixtures/xzip")

private func fixtureData(_ name: String) throws -> Data {
    try Data(contentsOf: fixtures.appendingPathComponent(name))
}

private final class ProgressRecorder: DecoderDelegate, @unchecked Sendable {
    private let lock = NSLock()
    private var values: [Double] = []

    func decoder(decoder: Decoder, path: String, progress: Double) {
        lock.lock()
        values.append(progress)
        lock.unlock()
    }

    var reports: [Double] {
        lock.lock()
        defer { lock.unlock() }
        return values
    }
}

private func makeDecoder(_ name: String, type: FileType, password: String?,
                         delegate: DecoderDelegate?) throws -> Decoder {
    let stream = try InStream(path: Path(fixtures.appendingPathComponent(name).path))
    let decoder = try Decoder(stream: stream, fileType: type, delegate: delegate)
    if let password {
        try decoder.setPassword(password)
    }
    try #require(try decoder.open(), "\(name) did not open")
    return decoder
}

/// Every item's bytes, keyed by path, extracted to memory.
private func extract(_ name: String, type: FileType = .sevenZ, password: String? = nil,
                     delegate: DecoderDelegate? = nil) throws -> [String: Data] {
    try extract(makeDecoder(name, type: type, password: password, delegate: delegate))
}

private func extract(_ decoder: Decoder) throws -> [String: Data] {
    let items = try decoder.items()
    let map = try ItemOutStreamArray()
    var streams: [(path: String, stream: OutStream)] = []
    for index in 0..<items.count {
        let item = try items.item(at: index)
        let stream = try OutStream()
        try map.add(item: item, stream: stream)
        streams.append((try item.path().description, stream))
    }
    _ = try decoder.extract(itemsToStreams: map)
    var result: [String: Data] = [:]
    for entry in streams {
        result[entry.path] = try entry.stream.copyContent()
    }
    return result
}

/// The exception an extraction fails with; records an issue if it does not fail.
private func failure(_ name: String, type: FileType = .sevenZ, password: String? = nil,
                     sourceLocation: SourceLocation = #_sourceLocation) throws -> Exception? {
    do {
        _ = try extract(name, type: type, password: password)
        Issue.record("\(name) extracted without an error", sourceLocation: sourceLocation)
        return nil
    } catch let exception as Exception {
        return exception
    } catch {
        Issue.record("\(name) failed with \(error), not a PLzmaSDK exception", sourceLocation: sourceLocation)
        return nil
    }
}

@Suite struct XzipDecoderTests {

    @Test(arguments: [
        "bzip2-by-7zip.7z",         // 7-Zip's own encoder, several 100k blocks
        "deflate-by-7zip.7z",
        "deflate64-rewrapped.7z",   // 7-Zip's Deflate64 stream in a hand-built archive
        "bzip2-garbage-after-stream.7z",
    ])
    func decodesToThePayload(_ name: String) throws {
        let payload = try fixtureData("payload.txt")
        let extracted = try extract(name)
        #expect(extracted.count == 1)
        #expect(extracted.first?.value == payload)
    }

    /// The case that needs Deflate64 rather than Deflate: a match 48 KiB back, outside Deflate's
    /// 32 KiB window. A decoder that only handled the shared subset would get this wrong.
    @Test func deflate64ReachesPastDeflatesWindow() throws {
        let far = try fixtureData("far.bin")
        #expect(try extract("deflate64-long-distance.7z")["far.bin"] == far)
    }

    @Test func anEncryptedDeflate64ItemDecodesWithTheRightPassword() throws {
        let payload = try fixtureData("payload.txt")
        #expect(try extract("aes-deflate64.7z", password: "1234")["payload.bin"] == payload)
    }

    /// The decoders report progress through the coder interface. Recorded rather than ignored, so a
    /// decoder that never called `SetRatioInfo` would show up as a single final report.
    @Test func decodingReportsProgress() throws {
        let recorder = ProgressRecorder()
        _ = try extract("bzip2-by-7zip.7z", delegate: recorder)
        let reports = recorder.reports
        #expect(reports.count > 1)
        #expect(reports == reports.sorted())
    }
}

@Suite struct XzipOperationResultTests {

    /// The `what` is unchanged from upstream, so anything matching on it keeps working; only the
    /// reason is new.
    @Test func theWhatIsUpstreamsAndTheReasonIsTheOperationResult() throws {
        let exception = try #require(try failure("copy-crc-mismatch.7z"))
        #expect(exception.what == "Item extracted with error.")
        #expect(exception.code == .internal)
        #expect(exception.reason == "crcError")
    }

    @Test(arguments: [
        ("unknown-method.7z", nil, "unsupportedMethod:0402FF"),
        ("zstd-method.7z", nil, "unsupportedMethod:04F71101"),
        ("aes-unknown-method.7z", "1234", "unsupportedMethod:0402FF 7zAES:19"),
    ] as [(String, String?, String)])
    func aMissingCoderIsNamedWithItsMethods(_ name: String, _ password: String?, _ reason: String) throws {
        let actual = try failure(name, password: password)?.reason
        #expect(actual == reason)
    }

    /// Our decoders return S_FALSE for every kind of bad stream, which 7-Zip reports as a data error.
    @Test(arguments: [
        "bzip2-truncated.7z", "bzip2-declared-longer.7z", "bzip2-declared-shorter.7z",
        "bzip2-concatenated.7z", "bzip2-garbage-instead-of-next-stream.7z", "bzip2-corrupt.7z",
        "deflate-truncated.7z", "deflate-declared-longer.7z", "deflate-declared-shorter.7z",
        "deflate64-truncated.7z", "deflate64-declared-longer.7z", "deflate64-declared-shorter.7z",
        "bzip2-bad-magic.7z", "deflate-invalid-block.7z", "deflate64-invalid-block.7z",
    ])
    func aBadStreamIsADataError(_ name: String) throws {
        let reason = try failure(name)?.reason
        #expect(reason == "dataError")
    }

    /// A flipped byte either breaks the stream's structure (data error) or decodes to wrong bytes
    /// that only the CRC catches; which one depends on where it lands.
    @Test(arguments: ["deflate-corrupt.7z", "deflate64-corrupt.7z"])
    func aCorruptedStreamIsADataOrCRCError(_ name: String) throws {
        let reason = try failure(name)?.reason
        #expect(reason == "dataError" || reason == "crcError", "got \(String(describing: reason))")
    }

    @Test func aWrongPasswordDecryptsToGarbageThatFailsAsDataOrCRC() throws {
        let reason = try failure("aes-deflate64.7z", password: "wrong")?.reason
        #expect(reason == "dataError" || reason == "crcError", "got \(String(describing: reason))")
    }

    @Test func aTruncatedXzIsAnUnexpectedEnd() throws {
        let reason = try failure("payload-truncated.xz", type: .xz)?.reason
        #expect(reason == "unexpectedEnd")
    }

    @Test func dataAfterAnXzStreamIsReported() throws {
        let reason = try failure("payload-trailing-garbage.xz", type: .xz)?.reason
        #expect(reason == "dataAfterEnd")
    }
}

@Suite struct XzipNamelessItemTests {

    private static func names(_ name: String) throws -> [String] {
        let decoder = try makeDecoder(name, type: .sevenZ, password: nil, delegate: nil)
        let items = try decoder.items()
        return try (0..<items.count).map { try items.item(at: $0).path().description }
    }

    /// A lone nameless item is "[Content]", the name 7-Zip falls back on.
    @Test func aLoneNamelessItemIsListedAndExtractedAsContent() throws {
        #expect(try Self.names("nameless-single.7z") == ["[Content]"])
        #expect(try extract("nameless-single.7z")["[Content]"] == (try fixtureData("payload.txt")))
    }

    /// Apache Commons Compress's `bla-nonames.7z`: two nameless items, numbered so neither overwrites
    /// the other. Upstream refused both with "Can't read item path.".
    @Test func severalNamelessItemsAreNumbered() throws {
        #expect(try Self.names("no-entry-names.7z") == ["[Content] 1", "[Content] 2"])
        let extracted = try extract("no-entry-names.7z")
        #expect(extracted["[Content] 1"]?.count == 82)
        #expect(extracted["[Content] 2"]?.count == 610)
    }

    /// Extracting to a directory takes a different path through the extract callback than
    /// extracting to streams, and has to name the files the same way.
    @Test func extractingToADirectoryWritesTheSameNames() throws {
        let decoder = try makeDecoder("no-entry-names.7z", type: .sevenZ, password: nil, delegate: nil)
        let dir = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: dir) }
        #expect(try decoder.extract(to: Path(dir.path)))
        let written = try FileManager.default.contentsOfDirectory(atPath: dir.path).sorted()
        #expect(written == ["[Content] 1", "[Content] 2"])
    }

    /// Commons Compress's `synthetic/long-name.7z`: a 32767-character name 7-Zip itself rejects with
    /// "Headers Error". An item whose name could not be *read* is not a nameless item, so it must not
    /// be given "[Content]" — that turned a broken header into a successful extraction of an empty
    /// file. It keeps upstream's refusal.
    @Test func anItemWhoseHeaderIsBrokenIsNotTreatedAsNameless() throws {
        #expect(try Self.names("long-name.7z") == [""])
        let decoder = try makeDecoder("long-name.7z", type: .sevenZ, password: nil, delegate: nil)
        let dir = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: dir) }
        let error = #expect(throws: Exception.self) { _ = try decoder.extract(to: Path(dir.path)) }
        #expect(error?.what == "Can't read item path.")
    }

    /// Testing an archive without writing it goes through the callback's third path-reading site.
    @Test func testingANamelessArchivePasses() throws {
        let decoder = try makeDecoder("no-entry-names.7z", type: .sevenZ, password: nil, delegate: nil)
        #expect(try decoder.test())
    }
}

@Suite(.serialized) struct XzipSolidExtractionTests {

    private static func processCPUSeconds() -> Double {
        var usage = rusage()
        getrusage(RUSAGE_SELF, &usage)
        func seconds(_ t: timeval) -> Double { Double(t.tv_sec) + Double(t.tv_usec) / 1_000_000 }
        return seconds(usage.ru_utime) + seconds(usage.ru_stime)
    }

    /// Commons Compress's COMPRESS-592: 70001 entries, 2.5 MB, one solid block. Upstream hands
    /// 7-Zip's Extract 256 indices at a time, and every call decodes the solid block from its start,
    /// so the block was decoded 274 times — quadratic in the entry count, ~5 s of CPU for 2.5 MB
    /// (7-Zip: 0.05 s). Decoding it once costs a fraction of a second of per-item bookkeeping.
    /// CPU time rather than wall time, so a loaded machine does not make it flaky; the margin is
    /// more than tenfold either way.
    @Test func aSolidBlockIsDecodedOnceNotOncePerBatch() throws {
        let decoder = try makeDecoder("COMPRESS-592.7z", type: .sevenZ, password: nil, delegate: nil)
        #expect(try decoder.count() == 70001)
        let before = Self.processCPUSeconds()
        #expect(try decoder.test())
        let used = Self.processCPUSeconds() - before
        #expect(used < 1.5, "testing 70001 entries of one solid block took \(used) s of CPU")
    }
}
